# Author: Andreas Rupp, LUT University, 2022.
# Copied from https://github.com/HyperHDG/HyperHDG/blob/main/.github/workflows/make_doxygen.yml

name: Doxygen

on: push

jobs:
  make_and_deploy_doxygen:
    name: Make and deploy doxygen
    runs-on: ubuntu-latest
    steps:
    - name: Install cmake
      run: sudo apt-get update; sudo apt-get install -y cmake
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run build and deploy action
      uses: HyperHDG/actions@doxygen
      with:
        # deploy_doxygen: ${{ github.ref == 'refs/heads/main' }}
        doxygen_command: eval "mkdir build && cd build && cmake .. && make doxygen && cd .."
        ci_repo_token: ${{ secrets.ECDFTOKEN }}
        ci_user_name: HyperHDG-CI
        ci_user_mail: HyperHDG@rupp.ink
        pages_repo_organization: AndreasRupp
        pages_repo_name: ecdf-estimator_auto-pages
        doxygen_path: build/html
